app = "railsapp"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "hkg"
console_command = '/rails/bin/rails console'

[build]


[env]
RAILS_ENV = "production"
PORT = '8080'
RAILS_LOG_TO_STDOUT = "t"
DATABASE_URL = "sqlite3:///data/storage/production.sqlite3"

[processes]
  app = './bin/rails server'

[mounts]
  source = "railsblocks_hd"
  destination = "/data/storage"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1